import type { SupportedLanguage } from "../../types/summary.js";

export function parseTargetLanguage(text: string): SupportedLanguage {
  const langMap: Record<string, SupportedLanguage> = {
    ja: "ja",
    japanese: "ja",
    en: "en",
    english: "en",
    zh: "zh",
    chinese: "zh",
    ko: "ko",
    korean: "ko",
    es: "es",
    spanish: "es",
    fr: "fr",
    french: "fr",
    de: "de",
    german: "de",
  };

  const input = text.trim().toLowerCase();
  return langMap[input] || "ja"; // Default to Japanese
}

export function formatSummaryForSlack(summary: {
  title: string;
  overview: string;
  decisions: string[];
  todos: Array<{ text: string; assignee?: string }>;
  blockers: string[];
  techNotes: string[];
}) {
  const blocks: Array<{
    type: string;
    text?: { type: string; text: string };
    elements?: Array<{ type: string; text: string }>;
  }> = [
    {
      type: "header",
      text: {
        type: "plain_text",
        text: summary.title,
      },
    },
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*Overview*\n${summary.overview}`,
      },
    },
  ];

  if (summary.decisions.length > 0) {
    blocks.push({
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*Decisions*\n${summary.decisions.map((d) => `• ${d}`).join("\n")}`,
      },
    });
  }

  if (summary.todos.length > 0) {
    const todoText = summary.todos
      .map((t) => `• ${t.text}${t.assignee ? ` (<@${t.assignee}>)` : ""}`)
      .join("\n");
    blocks.push({
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*TODOs*\n${todoText}`,
      },
    });
  }

  if (summary.blockers.length > 0) {
    blocks.push({
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*Blockers*\n${summary.blockers.map((b) => `• ${b}`).join("\n")}`,
      },
    });
  }

  if (summary.techNotes.length > 0) {
    blocks.push({
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*Technical Notes*\n${summary.techNotes.map((n) => `• ${n}`).join("\n")}`,
      },
    });
  }

  blocks.push({
    type: "context",
    elements: [
      {
        type: "mrkdwn",
        text: "_Generated by Slack Thread Summarizer_",
      },
    ],
  });

  return blocks;
}
